### PR TITLE
oncoprint - Add headers to heatmap track groups

### PR DESCRIPTION
**Pull request by adamabeshouse**
image

https://cbioportal-f-oncoprint-lguzrm4.herokuapp.com/results/oncoprint?Z_SCORE_THRESHOLD=2.0&cancer_study_id=coadread_tcga_pub&cancer_study_list=coadread_tcga_pub&case_ids=&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&heatmap_track_groups=coadread_tcga_pub_rna_seq_mrna_median_Zscores%2CKRAS%2CNRAS%2CBRAF%3Bcoadread_tcga_pub_methylation_hm27%2CKRAS%2CNRAS%2CBRAF&show_samples=false

### CODE REVIEW

**Comment by jjgao** [comment]
@adamabeshouse it looks great.

Adding @schultzn and @tmazor on this.

**Comment by tmazor** [comment]
@adamabeshouse it looks great! But I think I broke it? Go to the link below, click on the Heatmap menu, and try to add the data that appears by default (mRNA z-scores for BRAF KRAS EGFR ERBB2). When I click the Add button, nothing happens...

https://cbioportal-f-oncoprint-lguzrm4.herokuapp.com/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ccle_broad_2019&case_set_id=ccle_broad_2019_cnaseq&clinicallist=FRACTION_GENOME_ALTERED%2CHIST_SUBTYPE1%2CHIST_SUBTYPE2%2CHIST_SUBTYPE3&data_priority=0&gene_list=BRAF%2520KRAS%2520EGFR%2520ERBB2&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ccle_broad_2019_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ccle_broad_2019_mutations&heatmap_track_groups=ccle_broad_2019_CCLE_drug_treatment_zscore%2CAfatinib-1%2CAfatinib-2%2CAvagacestat-1%2CAvagacestat-2%3Bccle_broad_2019_rna_seq_mrna_median_Zscores%2CBRAF%2CKRAS%2CEGFR%2CERBB2&show_samples=false&tab_index=tab_visualize&treatment_list=Afatinib-1%3BAfatinib-2%3BAvagacestat-1%3BAvagacestat-2

**Comment by adamabeshouse** [comment]
@tmazor that is currently how it works - the data is already there, so "Add" does nothing. notice if you add an aditional gene then it will update. I have always felt this is strange behavior too, but that's what I was told to implement (aka not my fault! :) )

**Comment by jjgao** [comment]
@adamabeshouse maybe we should add a message above the `Add genes to heatmap button` once it's clicked? e.g. "Heatmap added", "Heatmap updated", "Genes are already in the heatmap". (@tmazor, please come up with better language :)

If may also be useful to add another message before clicking to tell the user that a heatmap for this profile has already been added and change the gene list and click the button will update the heatmap?

image

**Comment by tmazor** [comment]
Sorry this wasn't clear - I had deleted one of the tracks and so expected it to be re-added when I click add. This is normally the behavior - try the link below for an example of that. It's just that in that particular session, I managed to get to a point where that doesn't happen.

In general I do agree that we could have better wording/messaging as @jjgao suggested. But I think that can be a separate task. This issue was really about the very specific weird state that I managed to get into...


https://cbioportal-f-oncoprint-lguzrm4.herokuapp.com/results/oncoprint?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ccle_broad_2019&case_set_id=ccle_broad_2019_cnaseq&data_priority=0&gene_list=KRAS%2520EGFR&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ccle_broad_2019_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ccle_broad_2019_mutations&heatmap_track_groups=ccle_broad_2019_rna_seq_mrna_median_Zscores%2CEGFR&show_samples=false&tab_index=tab_visualize

**Comment by adamabeshouse** [comment]
@tmazor im still not able to reproduce the error - when i click add heatmap, it populates with the correct genes

**Comment by tmazor** [comment]
Sure @adamabeshouse 

Go to the link in my first comment
The mRNA z-score heatmap shows 2 genes: BRAF & KRAS
Click on the Heatmap menu. By default it suggests adding mRNA z-scores for BRAF KRAS EGFR ERBB2. Don't change anything, just click "Add"
Nothing happens. My expectation is that tracks for EGFR &ERBB2 will be added, but this doesn't happen.

If you do the same at the link in my second comment, the mRNA z-score heatmap updates to include all genes.

I've tried this in chrome & chrome w/ incognito window & firefox and it's reproducible from that first link.

Happy to chat/screenshare if that would be easier.

**Comment by adamabeshouse** [comment]
@tmazor ahha, so the issue is that those other two tracks actually are there, but they are hidden by scroll :). how should we solve this UI issue?

**Comment by tmazor** [comment]
sigh... thanks @adamabeshouse, i sure feel silly now...

I think that could be solved by having messages like @jjgao suggested so that the user has some indication that something happened -- similar to when you add a chart in study view. A message that says "Heatmap added" or "Heatmap updated" would inspire me to remember to scroll and look for it.

**Comment by tmazor** [comment]
How about a message below the "Add Heatmap" button that says one of:
<profile> added (first time adding a profile)
<profile> updated (adding new genes to an existing heatmap)
<profile> already contains these genes (all genes in list are already present in the heatmap)

**Comment by adamabeshouse** [comment]
@tmazor i created an issue for this, lets move discussion there

**Pull request merged**
