### PR TITLE
set showNA to false by default

### PR DESCRIPTION
**Pull request by olzhasmukayev**
Fix cBioPortal/cbioportal#10661 (see https://help.github.com/en/articles/closing-issues-using-keywords)

Describe changes proposed in this pull request:
- Remove NA fields on Study View Page by default

## Checks
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

## Any screenshots or GIFs?
No

## Notify reviewers
@alisman @inodb 
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

### CODE REVIEW

**Comment by olzhasmukayev** [comment]
Found issue with Bar charts loading. Try fix now

**Comment by alisman** [comment]
@inodb can you QA this and merge?

**Comment by olzhasmukayev** [comment]
> @inodb can you QA this and merge?

Hello! @alisman 

I found the bug in this code. This somehow breaks the Bar Chart view, where there is no NA toggle available. For example for this case: 

image

Adding the code in PR, would completely erase the view of the data: 

image

I spend over 3 days to understand why this happens, but i couldn't find the logical reason. Can someone help look into this issue?  

Thank you!

**Comment by olzhasmukayev** [comment]
I fixed the issue with the Bar Charts. The problems was with the conditions in the 

get labelShowingNA() function 
and 
get tickValuesBasedOnNA() function 

The reason for this was, because the showNAChecked is now false by default, but in the tickValuesBasedOnNA() function 

if (this.props.showNAChecked) -> the code will enter this block 

and this line 
const tickValuesWithoutNA = this.tickValues.slice(0, -this.numberOfNA);

will completely erase the actual numerical values. 
const tickValuesWithoutNA = this.tickValues.slice(0, -0); -> gives empty array 

Therefore, we need to introduce the additional if guards to the functions to handle empty conditions. 

Thank you!

**Review by inodb — APPROVED** [review]
LGTM! Just screenshots need to be updated

**Comment by olzhasmukayev** [comment]
Hi! 

Here are the screenshots of the barts with NA hidden by default. 

image

**Pull request merged**
