### PR TITLE
Normalize URL params in QueryStore, fixing bug when you paste in invalid OQL

### PR DESCRIPTION
**Pull request by adamabeshouse**
Fixes https://github.com/cBioPortal/cbioportal/issues/2722 and https://github.com/cBioPortal/cbioportal/issues/2723

# Checks
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

### CODE REVIEW

**Comment by ecerami** [comment]
hey @adamabeshouse:  I probably don't know enough to review this :-)

**Comment by adamabeshouse** [comment]
@ecerami oh I meant that you would test it out on heroku :)

**Comment by adamabeshouse** [comment]
@ecerami try this: https://cbioportal-pr-2730.herokuapp.com/

**Comment by ecerami** [comment]
@adamabeshouse:  thanks.  I tried the heroku instance and have verified that the two bugs are fixed.  Nice work!

**Comment by inodb** [comment]
Thanks everybody! Will try to deploy this at 5pm

**Pull request merged**
