### PR TITLE
Global settings menu for results view page

### PR DESCRIPTION
**Pull request by adamabeshouse**

### CODE REVIEW

**Comment by inodb** [comment]
@adamabeshouse Could you provide a more elaborate description for this PR? The PR titles and links to them show up directly in the relesease notes now (see e.g. https://github.com/cBioPortal/cbioportal-frontend/releases/tag/v3.1.5), so would be good to describe them in a way that someone with little knowledge of the code can understand at a high level what the changes are and why it is useful

**Comment by adamabeshouse** [comment]
cool @inodb

**Comment by inodb** [comment]
Thanks @adamabeshouse !

**Comment by inodb** [comment]
@adamabeshouse so is this the PR that introduces this menu 👇?
Screen Shot 2019-12-02 at 2 35 30 PM
If so, maybe good to add that screenshot

**Comment by adamabeshouse** [comment]
yeah @inodb :+1:

**Pull request merged**
