### PR TITLE
cbioObserver decorator - applies observer and auto disposes reactions on unmount

### PR DESCRIPTION
**Pull request by adamabeshouse**
do not merge: lets confirm the interface, then ill try to use it

### CODE REVIEW

**Comment by alisman** [comment]
this looks fine to me.

**Comment by adamabeshouse** [comment]
remoteData doesnt need a disposal because we took out the reactions from it - now that theyre computed its GC-able

**Comment by adamabeshouse** [comment]
reactiondisposer will get any mobx reaction, autorun as well

**Comment by adamabeshouse** [comment]
@alisman on further thought I dont think this is the best interface... bc the user has to create and assign member properties for each disposer

What I think would be better is to have the decorator create functions on the component: this.addReaction and this.addAutorun, which add the results to an internal list which componentWillUnmount goes through

**Comment by alisman** [comment]
"bc the user has to create and assign member properties for each disposer"  not sure i understand this. 
it seems reasonable to me that reactions should be made members of the class so they can be disposed.    lets remember that we should be using reactions very sparingly in the first place.  

also, if you wanted to add these extra methods, i think we would really have to create a subclass of React.Component to get the typing correct.  i would rather not go down this route.

**Comment by adamabeshouse** [comment]
@alisman sounds good.

are there any other things we want to roll into cbioObserver?

**Pull request closed without merging**
