### PR TITLE
Fix: added new screenshots

### PR DESCRIPTION
**Pull request by karannnnnnnnnnn**
Fix : cBioPortal/cbioportal
fixes #10477

Changes:

removed the old screenshots that were causing errors from /root/cbioportal-frontend/end-to-end-test/local/screenshots/reference from the folder and added new screenshots that support the Windows operating system.
removed characters ">" from the files so it does not generate an error.
There is no separate test for this but I have tested all other tests.

### CODE REVIEW

**Comment by karannnnnnnnnnn** [comment]
@alisman can you merge this ?

**Comment by alisman** [comment]
@karannnnnnnnnnn do you know why there's a package.json (and lock) included in this PR?

**Comment by karannnnnnnnnnn** [comment]
> @karannnnnnnnnnn do you know why there's a package.json (and lock) included in this PR?

**Comment by karannnnnnnnnnn** [comment]
@alisman i working on something else and i mistakenly added those file . sorry about that. should I do a new PR or something else?

**Comment by alisman** [comment]
No you can just get rid of those files, rebase and squash (to clean up git
history) and force push to the same PR. No reason to open a second (or
third PR)

**Comment by karannnnnnnnnnn** [comment]
@alisman is it fine now. The package.json file that you are seeing there is same as we are using in our main repo. so it,s not gonna make a problem when you merge it. let me know if you want something else.

**Comment by alisman** [comment]
@karannnnnnnnnnn it looks like the change is just one of formatting (on package.json) but I still don't want to merge it because it will confuse the git history for that file and cause problems when we introduce changes.   So you should try to figure out what settings cause the update to the formatting of the json.     Also, best the squash your commits (using interactive rebase).  We can do that in the Github interface on merge but it's better for you to tidy up the history and commit messages yourself.  Thanks for your contribution!

**Pull request closed without merging**
