### PR TITLE
change display name to display id

### PR DESCRIPTION
**Pull request by dippindots**
change header name to display id.
Fix # .

### CODE REVIEW

**Comment by ritikakundra** [comment]
@dippindots Can you send me the exact change in the attribute so I can add it to our data dict?

**Comment by dippindots** [comment]
@ritikakundra I changed the attribute name from `DISPLAY_SAMPLE_NAME` to `DISPLAY_SAMPLE_ID`. Do you think that's ok? If so, you make the same change in our data. Then we can have a test together.

**Comment by alisman** [comment]
@dippindots what's status of this PR?

**Comment by dippindots** [comment]
@alisman, @ritikakundra is work on changing this in the cohort, we will have a test when the data is ready.

**Comment by dippindots** [comment]
closed due to inactivity, please let me know if you still need this @ritikakundra .

**Pull request closed without merging**
