### PR TITLE
Using components from react-mutation-mapper for ClinVar and Gnomad columns

### PR DESCRIPTION
**Pull request by onursumer**
Fix cBioPortal/cbioportal/issues/6785

Related PRs: 

- cBioPortal/react-mutation-mapper/pull/80
- cBioPortal/react-mutation-mapper/pull/68
- cBioPortal/react-mutation-mapper/pull/118

# Checks
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

### CODE REVIEW

**Comment by onursumer** [comment]
@leexgh deployment is manual for frontend PRs. I have just initiated one, should be ready in a few mins.

**Comment by leexgh** [comment]
@onursumer thanks! All looks great 🙂 One minor thing is that we have a tooltip showing `Variant has no data in gnomAD.` when there is no gnomad data. Looks like mutation mapper doesn't have it?

**Comment by onursumer** [comment]
@leexgh good catch! Actually, the logic was copied over to mutation mapper, but seems like I have introduced a bug when doing that. I will open a PR for that in `react-mutation-mapper` and then update this PR.

**Comment by onursumer** [comment]
@leexgh I've updated the PR. Could you take a final look and confirm that everything looks good?

**Pull request merged**
