### PR TITLE
change the attribute from slideUrl to slideId

### PR DESCRIPTION
**Pull request by dippindots**
change the attribute from slideUrl to slideId
Fix https://github.com/cBioPortal/cbioportal/issues/5651

### CODE REVIEW

**Comment by dippindots** [comment]
@alisman This has been tested. And it is ready to review. Thank you!

**Comment by dippindots** [comment]
@jjgao I am guessing that all of the files on whole slide viewer is using ".svs" as their file type. Could you verify it is true? If there are lots of different file types, could we have more info in our data?

**Comment by jjgao** [comment]
@dippindots that's a question for Peter. Could you email him?

**Comment by dippindots** [comment]
@jjgao Yes, I will email him to verify this.

**Pull request merged**
