### PR TITLE
oncoprint, plots - add Other mutation type

### PR DESCRIPTION
**Pull request by adamabeshouse**

### CODE REVIEW

**Comment by pieterlukasse** [comment]
Hi @adamabeshouse, could you add some description and perhaps a screenshot to give this some context? Or perhaps a link to an issue that is solved by this? Thanks.

**Comment by adamabeshouse** [comment]
@pieterlukasse it's linked on github to the issue it fixes, in the future you can see that in the issues timeline or at the bottom. 
image
image

https://github.com/cBioPortal/cbioportal/issues/2779

**Comment by adamabeshouse** [comment]
I'll add a screenshot shortly

**Comment by adamabeshouse** [comment]
@pieterlukasse @jjgao the color maybe should change

image

image

**Comment by jjgao** [comment]
@adamabeshouse not sure if I like yellow. We should use the same color in mutations tab too (yellow is used when a dot is selected in mutations) -- could you change the color in Mutations tab and use the same color too? . Could you try to find another color?

**Comment by pieterlukasse** [comment]
thanks @adamabeshouse . I don't see this PR timeline...is this something I need to enable for my account? 
The screenshots look good. Perhaps brown is a good color.

**Comment by adamabeshouse** [comment]
@jjgao lets look together tomorrow, we don't have many options between all the mutation colors we already have, and the CNA and expression colors as well

**Pull request merged**
