### PR TITLE
fixed issue cbioportal#3039

### PR DESCRIPTION
**Pull request by jjgao**
# What? Why?
Fix https://github.com/cBioPortal/cbioportal/issues/3039

### CODE REVIEW

**Comment by jjgao** [comment]
The session service url generation code was looking for `?` to shorting the url. This is a somewhat hacky solution but soon enough we will remove the whole cross_cancer.do.

**Comment by jjgao** [comment]
could you merge and schedule it with the next release?

**Comment by inodb** [comment]
@jjgao OK! How do I reproduce the bug? Saving a cross_cancer session fails?

**Comment by jjgao** [comment]
@inodb the bookmark url does not truncating the part after #.

**Comment by jjgao** [comment]
@inodb has this been deployed? I still see the problem on the public portal.

**Pull request merged**
