### PR TITLE
Study view: support filters in url

### PR DESCRIPTION
**Pull request by kalletlak**
Fix https://github.com/cBioPortal/cbioportal/issues/4983

### CODE REVIEW

**Comment by jjgao** [comment]
https://cbioportal-f-feature-sv-vq8wz2.herokuapp.com/study?id=laml_tcga&filters={"clinicalDataFilters": [{"attributeId": "SEX","values": [{"value": "Female"}]}, {"attributeId": "AGE","values": [{"start": 25,"end": 30}, {"start": 30,"end": 35}, {"start": 35,"end": 40}, {"start": 40,"end": 45}, {"start": 45,"end": 50}, {"start": 50,"end": 55}, {"start": 55,"end": 60}, {"start": 60,"end": 65}, {"start": 65,"end": 70}, {"start": 70,"end": 75}, {"start": 75,"end": 80}]}],"mutatedGenes": [{"hugoGeneSymbols": ["FLT3", "NPM1"]}],"cnaGenes": [{"alterations": [{"alteration": -2,"hugoGeneSymbol": "FUS"}, {"alteration": 2,"hugoGeneSymbol": "KMT2A"}]}]}

**Comment by jjgao** [comment]
Thanks, @kalletlak.

Comments:

1. We may want to include the profile IDs for mutatedGenes and cnaGenes
2. Will svs / fusion genes also be supported?
3. why there are so many different groups for age in the example above? Shouldn't it just start from 25 and end with 80?
4. Should we update the url when selection changes?

**Comment by kalletlak** [comment]
@jjgao @zhx828 

> Comments:
> 
> 1. We may want to include the profile IDs for mutatedGenes and cnaGenes

Not sure what this is for. Is this in case if there are more than one mutation and cna profile for a study?

> 2. Will svs / fusion genes also be supported?

it does. here is an example
https://cbioportal-f-feature-sv-vq8wz2.herokuapp.com/study?id=hnsc_tcga_pan_can_atlas_2018&filters={"clinicalDataFilters":[{"attributeId":"SEX","values":[{"value":"Female"}]},{"attributeId":"AGE","values":[{"start":40,"end":45},{"start":45,"end":50},{"start":50,"end":55},{"start":55,"end":60},{"start":60,"end":65},{"start":65,"end":70},{"start":70,"end":75},{"start":75,"end":80}]}],"mutatedGenes":[{"hugoGeneSymbols":["EGFR"]}],"fusionGenes":[{"hugoGeneSymbols":["EGFR"]}],"cnaGenes":[{"alterations":[{"alteration":-2,"hugoGeneSymbol":"CDKN2A"}]}],"mutationCountVsCNASelection":{"xStart":0.08,"xEnd":0.4,"yStart":60.92307692307692,"yEnd":152.3076923076923},"studyIds":["hnsc_tcga_pan_can_atlas_2018"]}

> 3. why there are so many different groups for age in the example above? Shouldn't it just start from 25 and end with 80?

this is how bar char filter was designed. @zhx828 do you remember why this is this way.

> 4. Should we update the url when selection changes?

Not sure. currently we don't update url on selection changes

**Comment by jjgao** [comment]
>> 1. We may want to include the profile IDs for mutatedGenes and cnaGenes

> Not sure what this is for. Is this in case if there are more than one mutation and cna profile for a study?

Yes, and also we may need that once we load expression data.

>> 4. Should we update the url when selection changes?

> Not sure. currently we don't update url on selection changes

I think minimally we need i) a way to get the url with the filter, e.g. a link button like results page, and ii) when opening a url with filter and selection changes, we should either update the filter or remove the whole filter.

**Comment by kalletlak** [comment]
> > > 1. We may want to include the profile IDs for mutatedGenes and cnaGenes
> 
> > Not sure what this is for. Is this in case if there are more than one mutation and cna profile for a study?
> 
> Yes, and also we may need that once we load expression data.
> 
Here mutatedGenes and cnaGenes are for `Mutated Genes` and `CNA Genes` tables.
> > > 1. Should we update the url when selection changes?
> 
> > Not sure. currently we don't update url on selection changes
> 
> I think minimally we need i) a way to get the url with the filter, e.g. a link button like results page, and ii) when opening a url with filter and selection changes, we should either update the filter or remove the whole filter.

Ok

**Comment by zhx828** [comment]
> > 1. why there are so many different groups for age in the example above? Shouldn't it just start from 25 and end with 80?
> 
> this is how bar char filter was designed. @zhx828 do you remember why this is this way.

@jjgao @kalletlak The filter represents the groups which the backend determines. We don't do any bar chart filer parse at the frontend. If we want to support  [25, 80) in the url, so that logic needs to go back to backend and get dealt with.

**Comment by kalletlak** [comment]
> > > 1. why there are so many different groups for age in the example above? Shouldn't it just start from 25 and end with 80?
> > 
> > 
> > this is how bar char filter was designed. @zhx828 do you remember why this is this way.
> 
> @jjgao @kalletlak The filter represents the groups which the backend determines. We don't do any bar chart filer parse at the frontend. If we want to support [25, 80) in the url, so that logic needs to go back to backend and get dealt with.

@zhx828 @jjgao looks like backend api support both

```
{
	"clinicalDataFilters": [{
		"attributeId": "AGE",
		"values": [{
			"start": 20,
			"end": 40
		}]
	}],
	"studyIds": ["acc_tcga"]
}
```

```
{
	"clinicalDataFilters": [{
		"attributeId": "AGE",
		"values": [{
			"start": 20,
			"end": 40
		}, {
			"start": 25,
			"end": 30
		}, {
			"start": 30,
			"end": 35
		}, {
			"start": 35,
			"end": 40
		}]
	}],
	"studyIds": ["acc_tcga"]
}
```

return same results. I guess we need to update frontend

**Pull request merged**
