### PR TITLE
Extend LazyMobXTable to have resizable columns

### PR DESCRIPTION
**Pull request by rnugraha**
# What? Why?

These changes are supposed to add a new boolean prop to the table column so that whenever it's set to true it will make the column resizable.

Changes proposed in this pull request:
- Extend Column to have the resizable prop
- Install react-column-resizer lib

# Checks
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!
- [x] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [x] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

# Any screenshots or GIFs?
column-resizer

If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by rnugraha** [comment]
@adamabeshouse Sorry pushed wrong button

**Comment by alisman** [comment]
Could we make a column resizable in this PR so I can test it out?

**Comment by rnugraha** [comment]
> @rnugraha Could we make a column resizable in this PR so I can test it out?

Now, this PR also includes resizeable column. Please find them in the test data: `<YOUR_CBIO_URL>/patient?studyId=msk_impact_2017&caseId=P-0001104`

**Comment by Sjoerd-van-Hagen** [comment]
@inodb @alisman this PR has been open for some time. Can we get his merged ASAP so we do not have to waste time on rebasing?

**Comment by pvannierop** [comment]
@alisman raised concerns related to this feature via Slack. Proceeding with this feature depends on outcome of this discussion.

**Comment by jjgao** [comment]
@rnugraha the resizing functionality works nicely - good job. The double lines look a bit too heavy to me. Maybe we only need it in the header? And maybe one line would work?

**Comment by alisman** [comment]
@jjgao, Rize doesn't work for Hive anymore.   We kinda sat on this PR for a long time so I think it's on us to make any changes. I think what you've asked for should be accomplisheable via css.  We'll give it a try.

**Comment by alisman** [comment]
@jjgao @Sjoerd-van-Hagen

Here we have handle only at top.  Is this enough?
 
image

**Comment by jjgao** [comment]
@alisman is there a better way to indicate it's draggable? For example, in Google Drive, there is resize icon when hovering the board of left panel. Maybe we can do something similar? Another option is something similar to google sheet.

**Comment by jjgao** [comment]
Another comment: I just think this functionality will not be useful for the majority of the patients (probably all in public portal) since they don't have so many samples. That's why I think we shouldn't make it prominent.

**Comment by pvannierop** [comment]
@alisman I have updated the code so that `react-column-resizer` is added to missing.d.ts.

**Pull request merged**
