### PR TITLE
Global settings menu for results page

### PR DESCRIPTION
**Pull request by adamabeshouse**
@alisman styling help is invited

image

image

### CODE REVIEW

**Comment by alisman** [comment]
@adamabeshouse @jjgao  which other tabs are influenced by these global settings?  just curious.

I think the UI of the "Case type" select is not as intuitive as it is in oncoprint itself.  "Events by sample vs Events by patient" is super easy to grok.  Can we have same in global settings?

**Comment by alisman** [comment]
Is "VUS" a universally understood acronym amount our userbase?

**Comment by alisman** [comment]
I know the "cBioPortal > 10" labeling has existed forever in oncoprint, but i it's not totally clear what it means (at least to me!)

**Comment by alisman** [comment]
@adamabeshouse i think we could get rid of the "Settings" header in dropdown and just have  a header that better explains the the Patient/Sample control and is same size as rest of headers.  

Also, I think putting a horizontal rule under each section would be nice.

**Comment by adamabeshouse** [comment]
@alisman it affects the tabs listed here https://github.com/cbioportal/cbioportal/issues/5499

I agree with all your comments.. @jjgao what do you think about making it "cbioportal count" instead of just "cbioportal". or is that implied?

**Comment by adamabeshouse** [comment]
@alisman made changes, see updated screenshot above

**Comment by adamabeshouse** [comment]
@jjgao what design/placement are we thinking now for this?

**Comment by jjgao** [comment]
@adamabeshouse I think the position looks good. @alisman thoughts?

Does the global setting persist between sessions?

**Comment by adamabeshouse** [comment]
@jjgao 
> Does the global setting persist between sessions?
currently, no

**Comment by jjgao** [comment]
I think they should be included at least in the session / url.

I am not sure about persisting between sessions because opening a shared url may mess up with my setting. Maybe we can make it an option - save to my setting? If so, ideally we should save it to local storage.

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2838/files

**Pull request closed without merging**
