### PR TITLE
Make the EllipsisTextTooltip a block component

### PR DESCRIPTION
**Pull request by zhx828**
- Make the EllipsisTextTooltip a block component
- Remove property shownWidth (it was introduced in https://github.com/cBioPortal/cbioportal-frontend/pull/2110 to solve the scrollWidth is 0 issue, which has explained in the following link)
- Also let TrucatedText component supports `never` addTooltip

Based on the following article, the scrollWidth is not alwasy working especially in chrome. We are changing the component to a block component.
https://stackoverflow.com/questions/13226296/is-scrollwidth-property-of-a-span-not-working-on-chrome

### CODE REVIEW

**Comment by zhx828** [comment]
@adamabeshouse I agree. Any place wants to use the EllipsisTextTooltip should update the parent style considering this is a block element. Or use the TruncatedText for a inline component.

**Comment by alisman** [comment]
So, what's the process for merging this?  I mean, sounds like there need to be updates?

**Comment by zhx828** [comment]
@alisman all components where use the EllipsisTextTooltip have been either updated to new spec or changed to use TruncatedText. The pr should be good to go if there is no other code related issues.

**Comment by zhx828** [comment]
@alisman oh I'm gonna update the screenshots

**Comment by zhx828** [comment]
@alisman updated all screenshots.

I do think all 10 screenshots should be updated, @adamabeshouse just in case, could you take a look?

**Pull request merged**
