### PR TITLE
Don't fetch gene sets if no gene sets are provided

### PR DESCRIPTION
**Pull request by oplantalech**
Fix cBioPortal/cbioportal#3970.

### CODE REVIEW

**Comment by fedde-s** [comment]
Does it only apply to `rc`, or should it go to the release branch?

**Comment by inodb** [comment]
@fedde-s @oplantalech `release-1.12.0

**Comment by alisman** [comment]
this should have been against release-1.12.0 so i cherry-picked the commit and made another PR.

**Comment by fedde-s** [comment]
For reference: I believe it's PR #1030.

**Pull request closed without merging**
