### PR TITLE
fixed menu stretch in long confirmation messages

### PR DESCRIPTION
**Pull request by mhsh312**
Fix cBioPortal/cbioportal#10737

Describe changes proposed in this pull request:
- Fixed the Confirmation message widening the add chart menu
- Added max-width css property to `SuccessBanner` 
- Passed the `containerWidth` prop to `SuccessBanner` (similarly how it has been passed to `GeneLevelSelection`)
- Updated `ISuccessBannerProps` accordingly

Because the menu does not have an explicit width and just adjusts according to its children, setting max-width of `SuccessBanner` to 100% or inherit would not work. So, I passed the current `containerWidth` to `SuccessBanner` so that it can have a numerical limit to its width. 

> If no test is included it should explicitly be mentioned in the PR why there is no test.

It is a simple CSS fix so no extra tests are needed.

## Checks
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [x] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

## Any screenshots or GIFs?
image

## Notify reviewers
@alisman

### CODE REVIEW

**Review by alisman — APPROVED** [review]
Thank you @mhsh312 !

**Comment by alisman** [comment]
@mhsh312 There are some broken e2e tests.   Let me know if you have time to figure out what's up or need some help.
https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/12986/workflows/225289fc-d3ad-40dc-89bf-cb11c23b5cbd/jobs/158792
The instructions for running them are in the README

**Comment by mhsh312** [comment]
@alisman to be honest, I read the failed tests and I have no idea why this happened. Why did a css change break an API test? I could understand [this ](https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/12986/workflows/225289fc-d3ad-40dc-89bf-cb11c23b5cbd/jobs/158792) test maybe because it is written to perceive the UI a certain way and it is not finding it but absolutely no idea about the other two. The modified component also isn't used anywhere except the one mentioned in this issue.
Sorry, completely lost on this one.

**Comment by alisman** [comment]
Yeah, you don't have to worry about check sync test.  It's the remote
end-to-end-test  job that we need to fix:

https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/12986/workflows/225289fc-d3ad-40dc-89bf-cb11c23b5cbd/jobs/158792

If you look here, you'll see it's having trouble clicking on something.

[image: image.png]

**Comment by mhsh312** [comment]
> https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/12986/workflows/225289fc-d3ad-40dc-89bf-cb11c23b5cbd/jobs/158792

this test passed after I wrapped the `SuccessBanner` component instead of modifying it in [this](https://github.com/cBioPortal/cbioportal-frontend/pull/4892/commits/c3e175077c567859c3e5b63d6a4c31ae2da85d59) commit.

Check here:
https://app.circleci.com/pipelines/github/cBioPortal/cbioportal-frontend/12993/workflows/e5e7afaf-9b13-47df-bc7d-5b379d9eb436/jobs/158840

**Review by onursumer — APPROVED** [review]
Looks good to me! Not sure if the failing local db tests are related.

**Pull request merged**
