### PR TITLE
change text for mrna and protein

### PR DESCRIPTION
**Pull request by dippindots**
change the text for mRNA and protein from up/down-regulation to high/low.
Fix https://github.com/cBioPortal/cbioportal/issues/5529.

### CODE REVIEW

**Comment by dippindots** [comment]
Can use the study: chol_tcga(Provisional) to test the change. Thanks!

**Comment by jjgao** [comment]
@dippindots I was trying to test this but got an error for the following query:

http://cbioportal-frontend-pr-1950.herokuapp.com/results?Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_3way_complete&gene_list=EGFR%250ATP53&geneset_list=%20&tab_index=tab_visualize&Action=Submit&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&cancer_study_list=brca_tcga

image

**Comment by dippindots** [comment]
@jjgao Seems like it is an issue caused by recently master change. It also happens in Adam's new pr. I will report this to Aaron tomorrow. If you want to test it right now, can use the `http://www.cbioportal.org/` and setting `localStorage.heroku = 'cbioportal-frontend-pr-1950'` in the console.

**Comment by tmazor** [comment]
thanks @jjgao  - can someone let me know when this is deployed and i'll update the tutorials

**Comment by alisman** [comment]
@tmazor yes, this has been updated. sorry we didn't alert you sooner.

**Comment by tmazor** [comment]
No worries - I'll update the tutorial slides next week.

**Pull request merged**
