### PR TITLE
Group comparison: update group exclusion message

### PR DESCRIPTION
**Pull request by kalletlak**
Fix part-2 of https://github.com/cBioPortal/cbioportal/issues/8484
Fix https://github.com/cBioPortal/cbioportal/issues/8476

**Updated message**

Screen Shot 2021-04-14 at 10 27 45 AM
Screen Shot 2021-04-14 at 10 27 28 AM

### CODE REVIEW

**Review by adamabeshouse — APPROVED** [review]
clean!

**Comment by jjgao** [comment]
@kalletlak could you elaborate what are the changes in this PR? Thanks.

**Comment by kalletlak** [comment]
@jjgao is it changed from
Screen Shot 2021-04-16 at 1 19 11 PM
to 
Screen Shot 2021-04-16 at 1 19 19 PM

**Review by alisman — APPROVED** [review]

**Comment by jjgao** [comment]
@kalletlak I think I may have miscommunicated. We should revert to the previous sentence. "... in other tabs" should only be used in the `Overlap` tab.

The real issue is that the same message is displayed even when a user chooses to including overlapping samples and patients.

image

In that case, we should just remove that sentence about "completely overlapping..." from all tabs.

**Review by jjgao — CHANGES_REQUESTED** [review]
@kalletlak I think I may have miscommunicated. We should revert to the previous sentence. "... in other tabs" should only be used in the `Overlap` tab.

The real issue is that the same message is displayed even when a user chooses to including overlapping samples and patients.

image

In that case, we should just remove that sentence about "completely overlapping..." from all tabs.

E.g. in [this session](https://deploy-preview-3709--cbioportalfrontend.netlify.app/comparison/overlap?sessionId=5cf89323e4b0ab413787436c&selectedEnrichmentEventTypes=%5B%22missense%22%2C%22missense_mutation%22%2C%22missense_variant%22%2C%22indel%22%2C%22nonframeshift%22%2C%22inframe%22%2C%22inframe_del%22%2C%22inframe_deletion%22%2C%22in_frame_del%22%2C%22in_frame_deletion%22%2C%22nonframeshift_deletion%22%2C%22inframe_ins%22%2C%22inframe_insertion%22%2C%22in_frame_ins%22%2C%22in_frame_insertion%22%2C%22nonframeshift_insertion%22%2C%22truncating%22%2C%22feature_truncation%22%2C%22nonsense_mutation%22%2C%22nonsense%22%2C%22stopgain_snv%22%2C%22stop_gained%22%2C%22frameshift%22%2C%22frameshift_variant%22%2C%22frame_shift_del%22%2C%22frameshift_deletion%22%2C%22frame_shift_ins%22%2C%22frameshift_insertion%22%2C%22translation_start_site%22%2C%22initiator_codon_variant%22%2C%22start_codon_snp%22%2C%22start_codon_del%22%2C%22de_novo_start_outofframe%22%2C%22nonstop_mutation%22%2C%22stop_lost%22%2C%22splice_site%22%2C%22splice%22%2C%22splicing%22%2C%22splice_site_snp%22%2C%22splice_site_del%22%2C%22splice_site_indel%22%2C%22splice_region_variant%22%2C%22splice_region%22%2C%22silent%22%2C%22synonymous_variant%22%2C%22targeted_region%22%2C%22other%22%5D&comparisonId=6079ebfb72f8da5a0c954a40&overlapStrategy=Include), the first warning should be removed from all tabs.

image

**Comment by jjgao** [comment]
https://deploy-preview-3709--cbioportalfrontend.netlify.app/comparison/overlap?sessionId=5cf89323e4b0ab413787436c&selectedEnrichmentEventTypes=%5B%22missense%22%2C%22missense_mutation%22%2C%22missense_variant%22%2C%22indel%22%2C%22nonframeshift%22%2C%22inframe%22%2C%22inframe_del%22%2C%22inframe_deletion%22%2C%22in_frame_del%22%2C%22in_frame_deletion%22%2C%22nonframeshift_deletion%22%2C%22inframe_ins%22%2C%22inframe_insertion%22%2C%22in_frame_ins%22%2C%22in_frame_insertion%22%2C%22nonframeshift_insertion%22%2C%22truncating%22%2C%22feature_truncation%22%2C%22nonsense_mutation%22%2C%22nonsense%22%2C%22stopgain_snv%22%2C%22stop_gained%22%2C%22frameshift%22%2C%22frameshift_variant%22%2C%22frame_shift_del%22%2C%22frameshift_deletion%22%2C%22frame_shift_ins%22%2C%22frameshift_insertion%22%2C%22translation_start_site%22%2C%22initiator_codon_variant%22%2C%22start_codon_snp%22%2C%22start_codon_del%22%2C%22de_novo_start_outofframe%22%2C%22nonstop_mutation%22%2C%22stop_lost%22%2C%22splice_site%22%2C%22splice%22%2C%22splicing%22%2C%22splice_site_snp%22%2C%22splice_site_del%22%2C%22splice_site_indel%22%2C%22splice_region_variant%22%2C%22splice_region%22%2C%22silent%22%2C%22synonymous_variant%22%2C%22targeted_region%22%2C%22other%22%5D&comparisonId=60870c4872f8da5a0c954a62&overlapStrategy=Exclude&unselectedGroups=%5B%22Primary%22%5D&patientEnrichments=false

**Review by jjgao — APPROVED** [review]

**Pull request merged**
