### PR TITLE
Filter by TCGA PanCancer Atlas pathways in Results and Patient views

### PR DESCRIPTION
**Pull request by msalihaltun**
Fix cBioPortal/cbioportal#8286
Fix cBioPortal/cbioportal#8326

Add checkbox with label "Show TCGA PanCancer Atlas Pathways Only" to Results and Patient Views, checked by default.

### CODE REVIEW

**Comment by onursumer** [comment]
@jjgao Can you review the product (on netlify)? The actual implementation lives in pathway mapper repo, so there is not much code review here. If the functionality looks good, we can go ahead and merge the PR.

**Comment by inodb** [comment]
@cBioPortal/product can you take a look at this one?

**Comment by jjgao** [comment]
Thanks, @msalihaltun !

Maybe change the tooltip to:

"The pathways listed above were retrieved from [PathwayMapper](http://www.pathwaymapper.org/). When this option is checked, only the pathways under TCGA > PanCanAtlas will be shown. Uncheck to show all."

image

**Review by onursumer — APPROVED** [review]

**Comment by jjgao** [comment]
@msalihaltun thanks for the change. I am wondering if it's possible to hyperlink PathwayMapper (to pathwaymapper.org) and make it clickable (currently the tooltip will be gone when not hovering on the icon)?

**Comment by alisman** [comment]
@onursumer can you merge this when ready?

**Pull request merged**
