### PR TITLE
enrichments - improve axis padding for volcano and frequency plots

### PR DESCRIPTION
**Pull request by adamabeshouse**
image

### CODE REVIEW

**Comment by alisman** [comment]
@schultzn @adamabeshouse do you think we need a tick and dashed line to show actual zero? right now, someone might easily conclude that the data points are > 0.

**Comment by schultzn** [comment]
Can we do something like this?

image

**Comment by adamabeshouse** [comment]
@schultzn yes easily in fact thats the victory default behavior that i was working to avoid :p

**Comment by schultzn** [comment]
Maybe this is slightly better?

image

**Comment by adamabeshouse** [comment]
@schultzn isnt that the same as the suggestion you just made? yes ill see about doing that

**Comment by schultzn** [comment]
I modified it slightly - the dashed lines now don’t go all the way to the axes.

**Comment by adamabeshouse** [comment]
ohh I see

**Pull request merged**
