### PR TITLE
Oncoprint Add Track UI Tweak

### PR DESCRIPTION
**Pull request by aditygrg2**
Fix cBioPortal/cbioportal#10057

Describe changes proposed in this pull request:
Swapped the select fields on Oncoprint study view -> Add Track filters, which improves user experience for avoiding careful click after selecting and click "Add Track" button. 

Before:
Before

After:
After

### CODE REVIEW

**Comment by alisman** [comment]
@aditygrg2 thanks for this one.  One small thing, the Add Track button stretches verically as the list of items grows.    Seems like a small tweak will fix this nicely:
image

**Comment by aditygrg2** [comment]
Nice suggestion @alisman

Updated the PR, now the button is aligned at the center. I thought to take the button down (as the third row) but then the button was not visible when the second select field is elapsed, so this design looks good.

**Comment by alisman** [comment]
@aditygrg2 thanks for this one.  i'm trying to fix some end to end tests related to this change and did a couple force pushes to this branch FYI

**Comment by alisman** [comment]
@aditygrg2 thank you for this PR.  Apologies it took so long to merge.  There was an issue with our end-to-end tests

**Pull request merged**
