### PR TITLE
[READY TO MERGE] Making plot tabs more compact vertically

### PR DESCRIPTION
**Pull request by coderrsid**
fixing https://github.com/cbioportal/cbioportal/issues/5633

Making plot tabs slightly more compact vertically so that it fits a 13 inch screen easily.
Made it compact, decrease font-size, decrease white spaces and moved the colour-samples-options inside the plot and made the styles not applied to be global

Changes proposed in this pull request:
- Made it compact
- Decreased font-size
- Removed extra white space
- Moved colour sample options inside plot.

# Screenshots
Screenshot 2019-03-21 at 12 11 09 AM
Screenshot 2019-03-21 at 12 11 18 AM

# Notify reviewers
@schultzn @jjgao @alisman @adamabeshouse

### CODE REVIEW

**Comment by coderrsid** [comment]
@alisman I made the styles as you said so that they don't apply globally.

**Comment by coderrsid** [comment]
@adamabeshouse  Please review this one.

**Comment by jjgao** [comment]
@coderrsid Thanks for being persistent on this one. If possible, would you please stick to this PR instead of creating more every time you address comments? Please let us know if there is a reason that a new PR is needed.

**Comment by coderrsid** [comment]
@jigao I am just not able to understand the idea that how to make all the commits i've made even after you guys reviewed it and convert it to one single commit by rebasing or so. That's why i am making new pull requests.

**Comment by jjgao** [comment]
@coderrsid squashing can be done at the last step before merging. Before that, it's better to keep the flow of conversation once it's started.

**Comment by coderrsid** [comment]
Ohh sure @jjgao I will keep that in mind for future.. But can you please review this one?

**Comment by coderrsid** [comment]
Is there any more changes i should do @adamabeshouse @jjgao @alisman @inodb ?
This pull request has been there for long.

**Comment by adamabeshouse** [comment]
@coderrsid can you just rebase it on master and solve the conflicts? then we can merge

**Comment by adamabeshouse** [comment]
@coderrsid I made a new PR for you since youve already been going back and forth too much, I will handle merging it

https://github.com/cBioPortal/cbioportal-frontend/pull/2229

**Pull request closed without merging**
