### PR TITLE
Experiments with Guided Tour Options

### PR DESCRIPTION
**Pull request by ecerami**
closes https://github.com/cBioPortal/cbioportal/issues/7281
Experiments with Guided Tour Options.

## Checks
In Progress

## Any screenshots or GIFs?
In Progress 

## Notify reviewers
In Progress

### CODE REVIEW

**Comment by jjgao** [comment]
@ecerami I think we should move this forward. It is useful as is and this will open door to more tours. Maybe the team can take over?

**Comment by ecerami** [comment]
sure.  happy if others want to take this over.  also FYI @Luke-Sikina and @pieterlukasse are hiring a summer cBioPortal intern for the summer.

**Comment by jjgao** [comment]
@ecerami @Luke-Sikina @pieterlukasse Maybe the intern can help finish this one?

**Comment by Luke-Sikina** [comment]
@jjgao I think the answer is maybe, but probably not. This looks like it's the right level of difficulty for an intern, but it also looks like a significant amount of work. We already have a major intern assignment ([the installation map](https://github.com/cBioPortal/cbioportal/issues/7491)), so all I'm looking for at this point are some smaller, simpler assignments to help Joyce get comfortable.

**Comment by jjgao** [comment]
@Luke-Sikina sounds good, thanks! We'll find some other hands on this then.

**Comment by jjgao** [comment]
@alisman it would be good if we can resurrect this one later.

**Pull request closed without merging**
