### PR TITLE
Add e2e test for freqency calculation in study view on study with cal…

### PR DESCRIPTION
**Pull request by alisman**
Adds test for https://github.com/cBioPortal/cbioportal/issues/9163

A recent backend regression caused a problem with calculation of mutation frequency in study view for studies with called but unprofiled mutations.  This e2e test catches this condition on public impact study.

### CODE REVIEW

**Comment by alisman** [comment]
@inodb you think this is sufficient?

**Comment by inodb** [comment]
@alisman Thanks! For this study it only showed up in the SV table, see: https://master.cbioportal.org/study/summary?id=egc_mskcc_2020. If you can change it to take a screenshot from that table then yes it would be perfect 👍

**Comment by inodb** [comment]
@alisman ah actually never mind I was looking at the wrong study. You're right `msk_impact_2017` has it in the mutations table as well. Great - thanks!

**Review by inodb — APPROVED** [review]
Nice one! Thanks for the quick turnaround!

**Pull request merged**
