### PR TITLE
Move all study view configurations to AppConfig

### PR DESCRIPTION
**Pull request by zhx828**
This solves issue https://github.com/cBioPortal/cbioportal/issues/4778 and https://github.com/cBioPortal/cbioportal/issues/5016

### CODE REVIEW

**Comment by zhx828** [comment]
@inodb this is the study view configuration in frontendConfig. Equivalent to what we use in current configs.json. Let's update those portals once the pr is merged.

**Comment by zhx828** [comment]
@inodb yeah it works as is. As long as we add study_view in the json file, it will overwrite the front-end default. No backend changes needed

**Comment by alisman** [comment]
This seems like a whole lot of configuration.  Is it realistic that someone would want to change this on a instance basis?   Another issue is that with deep nested config structures, you can't configure just one property and fallback on defaults for everything else.  We could improve this.  We can merge this and then discuss later.  Food for thought.

**Comment by zhx828** [comment]
@alisman good point. Let's just keep whatever available in the current configs.json. Let's revisit before the release.

**Comment by zhx828** [comment]
@alisman  @kalletlak updated. In this round, let the backend supports table `tableAttrs` and `priority`. @inodb could you show me where you update the frontendConfig.json? I can update for the genie portal.

**Pull request merged**
