### PR TITLE
Re-add cancer studies bar chart visualization

### PR DESCRIPTION
**Pull request by oplantalech**
Reintroduce the cancer studies bar chart visualization which was removed in #3410.

### CODE REVIEW

**Comment by alisman** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/3644/files

@oplantalech you'll see in above recent PR, i removed chart.js from vendor file.  Lets add it back in this PR.

**Comment by oplantalech** [comment]
@alisman Done!

**Review by alisman — APPROVED** [review]

**Review by alisman — CHANGES_REQUESTED** [review]
I just found that the configuration property defaults to true in our properties example file.  I have to check with JJ whether we should make a new property so as to avoid turning it on for everyone again.

**Comment by Sjoerd-van-Hagen** [comment]
@alisman Hi Aaron,
I do not really understand what is happening here. For all the current installations your change will require them to update the portal properties to keep the functionality when they update. Now you are arguing that for new installations your approach is easier, but to me keeping this working in existing installations seems more important. People who set up a new installation are going to change the portal properties anyways so they can easily change the default value to something else.

To me the default behaviour should be the behaviour that has been the default for all this time, and not the new behaviour.

**Comment by alisman** [comment]
@jjgao can you comment on @Sjoerd-van-Hagen's feedback.   My understanding was that we retired this feature because we didn't think it was particularly valuable.   It has a bit of negative impact on performance of homepage and requires a library we would rather not load.  But if we were wrong about its' value to some then we should reconsider.

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen Thanks for the feedback. I vaguely remember this was discussed in a (probably steering) call and a couple of us decided this chart can be dropped due to the reason @alisman has mentioned. If you feel strongly that this chart has great value and should be kept, we can reopen the discussion.

I do think that we should have the freedom to remove features and code if they are not providing significant product value especially when they become a technical burden (e.g. previous Network tab) - inevitably, some users will be upset... I am curious how many of your clients asked for this feature to be restored?

**Comment by Sjoerd-van-Hagen** [comment]
Hi @jjgao , let me check with the client to see how important this is. Perhaps they have a use case.

**Comment by Sjoerd-van-Hagen** [comment]
@jjgao @alisman Discussed this with the client, it is fine to remove.

**Pull request closed without merging**
