### PR TITLE
Using Data Access Tokens mouseover

### PR DESCRIPTION
**Pull request by ao508**
Data Access Tokens dropdown menu now includes mouseover on "Download token" that links out to Web API page where how to create DAT is described and there is a button for users to click to generate and save the Data Access Token file to their file system.

Screen Shot 2019-10-09 at 9 22 07 AM

Added new property to set the default doc page describing how to use data access tokens. (This property needs to be added to `cbioportal/src/main/resources/portal.properties.EXAMPLE` as well. 

Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

# Checks
- [ ] Has tests or has a separate issue that describes the types of test that should be created. If no test is included it should explicitly be mentioned in the PR why there is no test.
- [ ] The commit log is comprehensible. It follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). It can help to figure out who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them either through slack or by assigning them as a reviewer on the PR

### CODE REVIEW

**Comment by alisman** [comment]
@ao508 I don't think having the link to the page in the tooltip makes sense.  I would recommend that the dropdown button open a new tab where the user can obtain a token.  I think the link text should be "API Access Tokens"

**Comment by ao508** [comment]
@n1zea144 Can you comment on this? Do you think we should keep the token download functionality here in the dropdown menu or make a tab that shows the DAT documentation and also has a button (or link) that download the token for the user. 
https://github.com/cBioPortal/cbioportal-frontend/pull/2765#issuecomment-540804778

**Comment by alisman** [comment]
@alisman just to clarify my point:  I don't think "Download token" is specific enough language whether we have a tooltip or not.  It could be "Download data access token"

**Comment by jjgao** [comment]
I like @alisman's idea.

**Comment by schultzn** [comment]
I agree, a tooltip won't work. It could just be a third item in the list:
1 - Sign out
2 - Download data access token
3 - Help about data access tokens

Or, here is what ICGC does in their portal: 
Once you login, the token manager icon shows up.. and when you click on that, you get more information. Probably not what we should do for cBioPortal.
image

**Comment by n1zea144** [comment]
Hi @ao508, I spoke with @alisman about this a short while ago.  We came up with a proposed solution.  What we would like do is change the current "Download Token" action so that instead of initiating a request for a token, it takes the user to the web-api tab.  We can add a Data Access Token Section to this page (maybe after the introduction) that describes how a token is required to access a password protected portal.  At this point, we can have the action to download the token.

The fact that we are directing a user's attention to this page makes me wonder if we should update the docs, remove the old webservice.do text and, at least, link to the swagger page, despite not having officially released the web service.

Thoughts?
@jjgao @schultzn

**Comment by jjgao** [comment]
That's a good idea. It would also be good to add links to the token doc section in other places such as R/Matlab and swagger page.

**Pull request closed without merging**
