### PR TITLE
fix: fixed-local-setup-issue-windows

### PR DESCRIPTION
**Pull request by karannnnnnnnnnn**
Fix : cBioPortal/cbioportal
fixes #10477

Changes:

removed the old screenshots that were causing errors from /root/cbioportal-frontend/end-to-end-test/local/screenshots/reference from the folder and added new screenshots that support the Windows operating system.
removed characters ">" from the files so it does not generate an error.
There is no separate test for this but I have tested all other tests.

### CODE REVIEW

**Comment by karannnnnnnnnnn** [comment]
@alisman can you review it?

**Comment by karannnnnnnnnnn** [comment]
@asliman can you review it . it fixes all errors now

**Comment by alisman** [comment]
@karannnnnnnnnnn merged! please note, due to a delicate issue right how, we are merging PRs to a branch called temp-master.   This should be resolved in next few days.  But no further work is necessary from you on this.

**Comment by karannnnnnnnnnn** [comment]
thanks @alisman

**Pull request merged**
