### PR TITLE
Using API proxy for cancer hotspots and 3d hotspots

### PR DESCRIPTION
**Pull request by onursumer**
# What? Why?
Updated hotspots API root URLs to use the proxy end point

# Checks
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

### CODE REVIEW

**Comment by onursumer** [comment]
[(5) update url to use proxy api for oncokb, cancerhotspot & 3dhotspots](https://trello.com/c/ZUoISG8J/130-5-update-url-to-use-proxy-api-for-oncokb-cancerhotspot-3dhotspots)

**Comment by ersinciftci** [comment]
I think we should set them in a properties file.

**Comment by onursumer** [comment]
@adufilie @alisman @inodb: do we have a default properties file where we set these kind of values?

**Comment by alisman** [comment]
@adufilie @alisman @inodb There is another PR with a new configuration module.

**Pull request merged**
