### PR TITLE
Switch urls for datahub downloads in datasets page

### PR DESCRIPTION
**Pull request by alisman**
Issue: https://github.com/cBioPortal/cbioportal/issues/3824

# What? Why?
Fix # .

Changes proposed in this pull request:
- a
- b

# Checks
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by alisman** [comment]
@jjgao @yichaoS  it turns out we call github's list service to determine if the study has corresponding data.  How can we tackle this in new hosted situation?

**Comment by jjgao** [comment]
@yichaoS maybe we can have a file on the server listing all studies?

**Comment by n1zea144** [comment]
@adamabeshouse @alisman: @yichaoS mentioned that there was concerning about not having a table of contents on the page to determine what studies are available.  Is that right?  I think there may be a setting in Apache to visually display the file system on the page.  Another option is to keep a list of studies on a file in the sample location.  Any thoughts on this?

**Comment by jjgao** [comment]
@n1zea144 it may be better to keep a file (ideally in JSON format) so that we don't have to write parsing code in the frontend. Some code would be needed to generate the file in the pipeline though.

**Pull request merged**
