### PR TITLE
Render splice mutations separately

### PR DESCRIPTION
**Pull request by adamabeshouse**
Fixes https://github.com/cBioPortal/cbioportal/issues/7857

image

image

[Link](https://beta.cbioportal.org/results/oncoprint?session_id=5bd3ccdf498eb8b3d56887fb&plots_horz_selection=%7B%22dataType%22%3A%22MUTATION_EXTENDED%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D)

I don't think the color choice is ideal, let's discuss

### CODE REVIEW

**Comment by jjgao** [comment]
Thanks, @adamabeshouse. I think the color is a bit too close to inframe. Maybe we can try (dark) navy blue for splice driver and a light version for splice vus?

**Comment by adamabeshouse** [comment]
@jjgao wouldnt that totally blend in with CNA del?

**Comment by adamabeshouse** [comment]
here are all the current oncoprint colors
oncoprint colors

**Comment by jjgao** [comment]
maybe we can try #000080 for splice driver? It's close to black. 

image

Not sure what would be a good one for splice vus though.. maybe #8093b0? it's close to truncting vus.
image

**Comment by adamabeshouse** [comment]
@jjgao another idea: would splice be considered very close conceptually to truncating? maybe we can use truncating colors and add a line or something

**Comment by jjgao** [comment]
@adamabeshouse yes, it's close to truncating. I think it might be better to choose a color that is close to truncating instead of creating more styles.

**Comment by adamabeshouse** [comment]
@jjgao I understand your point but I also think it's confusing to add more colors that are extremely close to each other.. I'm not sure which is more confusing/useful.

**Comment by schultzn** [comment]
How about shades of orange? I think the below would work -- and sorry if you have already tried that

image

**Comment by schultzn** [comment]
Fixed the legend
image

**Comment by adamabeshouse** [comment]
thanks @schultzn but isn't it very close to inframe?

**Comment by adamabeshouse** [comment]
@schultzn I think those colors are different enough, but visually they are a bit closer to inframe (brown) than to splice (black), right? if its not a problem then I think those colors would work

**Comment by schultzn** [comment]
I think that is fine - as long as they are distinct enough.

**Comment by adamabeshouse** [comment]
@schultzn @jjgao @alisman I made the change using the colors that @schultzn suggested. What do you think?

**Review by alisman — APPROVED** [review]

**Pull request merged**
