### PR TITLE
Dynamic resize for MDACC Heatmap iframe on study page

### PR DESCRIPTION
**Pull request by ChrisWakefield**
# What? Why?
Fix #5981 .
IFrame height was hard-coded to 700px.  This changes it to dynamically resize, with a minimum height of 700.

Changes proposed in this pull request:
- Modify IFrameLoader to allow CSS class name
- Assign class name to iframe and add styles specific to this class

# Checks
- [ ] Is this PR adding logic based on one or more **clinical** attributes? If yes, please make sure validation for this attribute is also present in the data validation / data loading layers (in backend repo) and documented in [File-Formats Clinical data section](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#clinical-data)!
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [x] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:
@zhx828 @alisman

### CODE REVIEW

**Comment by ChrisWakefield** [comment]
Failed screenshot compare.  Is likely to be expected?

**Comment by alisman** [comment]
@dippindots i thought we had taken care of this issue already, no?

**Comment by dippindots** [comment]
@alisman No, we solved the iframe issue in patient view page, not for study view. I think this is a new issue.

**Comment by alisman** [comment]
@ChrisWakefield thanks for doing this.  when i test this on heroku it doesn't seem to be working.
https://cbioportal-frontend-pr-2227.herokuapp.com/study?id=brca_tcga_pub&tab=heatmaps

Does it work locally for you?  I actually don't see the iframe class written to iframe element.  Just curious if it works locally for you.

**Comment by ChrisWakefield** [comment]
@alisman Thanks for looking into this!  I think I see the same thing (class is not added to iframe, height is still fixed at 700 in the style).  That looks like output of the old code without my PR.  ?

**Comment by jjgao** [comment]
fixed https://github.com/cBioPortal/cbioportal/issues/5981

**Pull request merged**
