### PR TITLE
oncoprint - add option to show oql filters as "sublabels" in tracks

### PR DESCRIPTION
**Pull request by adamabeshouse**
image

image

Im not showing them in merged tracks, but they do show in the expansions as seen in screenshot

### CODE REVIEW

**Comment by schultzn** [comment]
Looks good! I assume the full OQL shows up upon mouseover?

**Comment by pieterlukasse** [comment]
Nice :+1:

**Comment by jjgao** [comment]
somehow I couldn't deploy to heroku...

@adamabeshouse when a user is explicitly using oql, are you displaying them by default?

**Comment by adamabeshouse** [comment]
no, the default is off. but we can do that instead - if user specifies OQL then we'll turn it on by default

**Comment by adamabeshouse** [comment]
no, the default is off. but we can do that instead - if user specifies OQL then we'll turn it on by default

**Comment by jjgao** [comment]
@adamabeshouse I think that would be good.

**Comment by pieterlukasse** [comment]
@adamabeshouse should this have gone to `master` instead of `rc`?

**Comment by adamabeshouse** [comment]
@pieterlukasse ah maybe. i thought it was small enough to go to master

**Pull request merged**
