### PR TITLE
Coloring clinical value alive and not progressed; Support clinical value with multiple words

### PR DESCRIPTION
**Pull request by zhx828**
Also include the combination that all words are camel cased

# What? Why?
Fix https://github.com/cBioPortal/cbioportal/issues/6292#event-2425315229

### CODE REVIEW

**Comment by zhx828** [comment]
@adamabeshouse I'm not so sure the proper way to deal with the clinical value format. Ideally, we should remove all spaces and lowercase the value, don't bother doing camel case/upper case etc. But seems oncoprint at the moment only accepts the exact match. Any thoughts?

**Comment by adamabeshouse** [comment]
@zhx828 yeah. we could make an update to the oncoprint library to take a function for `category_to_color` so we don't have to do this. would that be better or is this okay for now?

**Comment by zhx828** [comment]
@adamabeshouse it's ok for now, just when we see more extreme cases, then we should update oncoprint.

**Comment by zhx828** [comment]
The failing test is not related to this PR.

**Pull request merged**
