### PR TITLE
Change attribute ids of special clinical attributes

### PR DESCRIPTION
**Pull request by adamabeshouse**

### CODE REVIEW

**Comment by alisman** [comment]
@jjgao merging this would break some of the urls that might be out there with integer values for clinical attributes.  Do you think we should go through the trouble of maintaining compatibility with those (they have only been in place since yesterday)

**Comment by jjgao** [comment]
@alisman not worries about existing ones.

**Comment by jjgao** [comment]
@alisman for old urls, it's ok if a track is not displayed, but the oncoprint should still load.

**Comment by alisman** [comment]
@adamabeshouse can you confirm that's the case?

**Comment by adamabeshouse** [comment]
@alisman @jjgao fixed now, it wont break

**Comment by alisman** [comment]
@adamabeshouse e2e test that is failing now looks it might actually be legit?

**Comment by adamabeshouse** [comment]
I'm almost positive that would be because I updated a link in the tests to use FRACTION_GENOME_ALTERED instead of 1, and currently in production that wont load the correct clinical tracks, which is going to break that

**Comment by adamabeshouse** [comment]
oh oops, no I actually forgot to change another link in the e2e tests. tests.. they work

**Pull request merged**
