### PR TITLE
fixes issue #246

### PR DESCRIPTION
**Pull request by Rohanhacker**

### CODE REVIEW

**Comment by Rohanhacker** [comment]
also fixes issue #205 

screenshot from 2017-03-25 23-09-17

**Comment by alisman** [comment]
Hi Rohan, 

Thank you so much for doing this. Unfortunately, the master branch is very out of date and we have actually switched from Redux to Mobx.   So the connector code is out of date and I can't use this.  Are you a GSOC candidate?

**Comment by Rohanhacker** [comment]
yup @alisman sorry I didn't know that

**Comment by alisman** [comment]
Apologies.  Have you been in touch with @inodb?  He is the coordinator for GSOC here and we can steer you to a necessary task.

**Comment by inodb** [comment]
@Rohanhacker No worries! Thanks for giving this a shot! Maybe try to rebase on the "integration" branch. Do you know how? I also just added you to the slack channel, so feel free to ask questions there. Thanks!

**Comment by adufilie** [comment]
Can this be closed since those issues don't exist in the integration branch?

**Pull request closed without merging**
