### PR TITLE
Multiple genome support : accommodating changes made to the database

### PR DESCRIPTION
**Pull request by khzhu**
# What? Why?
support multiple reference genome builds

Changes proposed in this pull request:
- filter genetic profile by the type of genetic alternation
- retrieve copy number segment data by genetic profile id
- pull chromosome sizes from json data file
- display chromosome name from **chr** property of mutation data

# Checks
- [ ] Follows [7 rules of great commit messages](http://chris.beams.io/posts/git-commit/). For most PRs a single commit should suffice, in some cases multiple topical commits can be useful. During review it is ok to see tiny commits (e.g. Fix reviewer comments), but right before the code gets merged to master or rc branch, any such commits should be squashed since they are useless to the other developers. Definitely avoid [merge commits, use rebase instead.](http://nathanleclaire.com/blog/2014/09/14/dont-be-scared-of-git-rebase/)
- [ ] Follows the [Airbnb React/JSX Style guide](https://github.com/airbnb/javascript/tree/master/react).
- [ ] Make sure your commit messages end with a Signed-off-by string (this line
  can be automatically added by git if you run the `git-commit` command with
  the `-s` option)

# Any screenshots or GIFs?
If this is a new visual feature please add a before/after screenshot or gif
here with e.g. [GifGrabber](http://www.gifgrabber.com/).

# Notify reviewers
Read our [Pull request merging
policy](../CONTRIBUTING.md#pull-request-merging-policy). If you are part of the
cBioPortal organization, notify the approprate team (remove inappropriate):

@cBioPortal/frontend

If you are not part of the cBioPortal organization look at who worked on the
file before you. Please use `git blame <filename>` to determine that
and notify them here:

### CODE REVIEW

**Comment by pieterlukasse** [comment]
adding 217 files! Seems wrong. It looks like all type of build artifacts are being added here.
@alisman can you comment?

**Comment by pieterlukasse** [comment]
should you make the PR to `rc` ?

**Comment by jjgao** [comment]
Yes, please rebase/squash to `rc`.

**Comment by khzhu** [comment]
@jjgao, I will rebase to rc on Monday. Thanks!

**Comment by khzhu** [comment]
@jjgao @inodb @pieterlukasse 
rebased to the latest RC and committed 14 files, but somehow 165 files changed shows up. Anything could be cause of this? Thanks!

- git status before commit:

> [Tue Oct 03 13:19:36 kelsyzhu@tpugh25:~/myspace/cbioportal-frontend](multiple-genome-support) $ git status
> On branch multiple-genome-support
> Your branch and 'origin/multiple-genome-support' have diverged,
> and have 24 and 2 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
> 
> 	modified:   src/pages/patientView/clinicalInformation/PatientViewPageStore.ts
> 	modified:   src/pages/patientView/genomicOverview/Tracks.tsx
> 	new file:   src/pages/patientView/genomicOverview/chromSizes.json
> 	modified:   src/pages/patientView/genomicOverview/tracksHelper.ts
> 	modified:   src/shared/api/generated/CBioPortalAPI-docs.json
> 	modified:   src/shared/api/generated/CBioPortalAPI.ts
> 	modified:   src/shared/api/generated/CBioPortalAPIInternal-docs.json
> 	modified:   src/shared/api/generated/CBioPortalAPIInternal.ts
> 	modified:   src/shared/components/mutationTable/column/ChromosomeColumnFormatter.tsx
> 	modified:   src/shared/components/query/gene_lists.ts
> 	modified:   src/shared/constants.ts
> 	modified:   src/shared/lib/StoreUtils.ts
> 	modified:   src/test/CivicMockUtils.ts
> 	modified:   src/test/MutationMockUtils.ts

- git log after commit:

> [Tue Oct 03 13:41:32 kelsyzhu@tpugh25:~/myspace/cbioportal-frontend](multiple-genome-support) $ git reflog
> 404e4c9 HEAD@{0}: commit: replace gene.chromosome with mutation.chromosome, read chromosome sizes from json file, use new molecular profile id when fetch segments
> cf6d977 HEAD@{1}: rebase finished: returning to refs/heads/multiple-genome-support
> cf6d977 HEAD@{2}: rebase: checkout upstream/rc
> 2a53138 HEAD@{3}: reset: moving to HEAD
> 2a53138 HEAD@{4}: rebase finished: returning to refs/heads/multiple-genome-support
> 2a53138 HEAD@{5}: rebase: checkout upstream/rc

**Comment by jjgao** [comment]
@khzhu the pr was still pointing to `master` branch. I just changed it to `rc` and looks like there is only one commit now :)

**Comment by khzhu** [comment]
@jjgao, now looks good, thank you!

**Comment by inodb** [comment]
@khzhu So is it correct that the multiple reference genome support only affects the genomic track on the patient view?

I imagine the annotations might change as well for oncokb/hotspots etc. I guess between grch37 and 38 there is prolly little difference. But just trying to get an idea of how much work it is to truly support multiple reference genomes and what the goals are in that respect. Do we have any documentation on this feature? I don't see it in the RFCs. https://github.com/cBioPortal/cbioportal/blob/master/docs/RFC-List.md

**Comment by jjgao** [comment]
@inodb I'll affect everywhere that we use genomic location. Currently, OncoKB/Hotspot are on protein positions so it won't affect that, but later if we want to switch to genomic based (and probably through GenomeNexus), we need to do some work there.

**Comment by khzhu** [comment]
@inodb @jjgao, sorry I was away. Currently, the multiple reference genome support only affects genomic tracks and the copy number alteration table on the patient view.
I can get RFC drafted. Does new RFC need be reviewed before submission? Also, since most changes are at backend, do I need two RFCs or just one for both front and backend? Thanks!

**Comment by alisman** [comment]
@inodb what's story with this PR?

**Comment by khzhu** [comment]
Hi @alisman, to make a long story short, we have changed the plan (#3707) and this PR is no longer valid. I will close it. Sorry for the confusion!

**Pull request closed without merging**
