### PR TITLE
Study view: reset filters when custom cases are selected

### PR DESCRIPTION
**Pull request by kalletlak**
Fix https://github.com/cBioPortal/cbioportal/issues/6974

New warning message

Screen Shot 2020-01-22 at 2 10 33 PM

### CODE REVIEW

**Comment by alisman** [comment]
@kalletlak it think it should be "Submitting will clear all filters"  

@jjgao I actually think this UI is pretty confusing.  You click "all selected samples" to populate the textarea, and THEN click "select" button.   It's like, select selected samples.    Maybe the button should read "View only above listed samples/patients"

**Comment by jjgao** [comment]
@kalletlak: discussed @alisman - let's make the changes below:

- change the message to "Submitting will clear all filters"
- change "all selected" and "all unselected" to "currently selected" and "currently unselected"
- make the ui bigger if necessary

**Comment by jjgao** [comment]
@kalletlak could you connect with the issue?

**Comment by kalletlak** [comment]
> @kalletlak could you connect with the issue?

@jjgao I don't see an option to connect to issue. But anyways its in the pr description.

**Comment by jjgao** [comment]
@kalletlak the connect option is avaiable if you install the zenhub app. It helps us to moving issues into review stage.

**Comment by jjgao** [comment]
@tmazor could you help review this quickly.

**Comment by tmazor** [comment]
Looks ok to me! I suggest a few small wording tweaks to make it even clearer:
- Change the warning to: "Submitting will clear current filters."
- Change the button from "Select" to "Filter to listed samples/patients [change text based on radio button selection]"

**Comment by kalletlak** [comment]
@tmazor @jjgao @alisman updated. Could you review it again

**Comment by tmazor** [comment]
Looks good to me @kalletlak !

**Pull request merged**
