### PR TITLE
disable mouse event for oncoprint tests

### PR DESCRIPTION
**Pull request by dippindots**
Disable mouse event for oncoprint tests
Fix # https://github.com/cBioPortal/cbioportal/issues/6325.

### CODE REVIEW

**Comment by dippindots** [comment]
@alisman it works for SVG, same as the Venn diagram.

**Comment by adamabeshouse** [comment]
@dippindots the mouse events that are problematic with the oncoprint actually occur on `canvas` objects, not svg. so hopefully this will still work

**Comment by dippindots** [comment]
Thanks for pointing this out @adamabeshouse. I tested it again, and it works fine!

**Comment by alisman** [comment]
The problem is quite intermittent so only time will tell if it's really fixed.

**Pull request merged**
