### PR TITLE
SV: ignore alterationFilter while checking initial filter state

### PR DESCRIPTION
**Pull request by kalletlak**
Fix https://github.com/cBioPortal/cbioportal/issues/8805

### CODE REVIEW

**Review by adamabeshouse — APPROVED** [review]
LGTM 🚀

**Review by dippindots — APPROVED** [review]
👍

**Review by inodb — COMMENTED** [review]
@kalletlak Thanks for fixing this! Just curious - does this fully address the bug? Is it correct that the issue might still show up if one were to share a link with a driver annotation?

**Comment by kalletlak** [comment]
Currently driver annotation are not yet supported in URL. It might need some updates when it is enabled

**Pull request merged**
