### PR TITLE
Group list tweaks

### PR DESCRIPTION
**Pull request by adamabeshouse**

### CODE REVIEW

**Comment by jjgao** [comment]
I am wondering if we can also move the "Exclude..." drop down to the line of the study name?

image

**Comment by adamabeshouse** [comment]
@jjgao I don't see how?

**Comment by jjgao** [comment]
like this?

image

**Comment by adamabeshouse** [comment]
@jjgao oh sorry I misread, thought you wanted it with the groups. I think that looks good

**Comment by adamabeshouse** [comment]
@jjgao done 
image

**Pull request merged**
