### PR TITLE
Waterfall plot title shows treatment name (not stable_id)

### PR DESCRIPTION
**Pull request by pvannierop**
# Problem
The title in the waterfall plot showed the `stable_id` of treatments rather than the `name`.

# Fix
The title now shows the `name`.

# Link
https://www.cbioportal.org/results/plots?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=ccle_broad_2019&case_set_id=ccle_broad_2019_cnaseq&data_priority=0&gene_list=AKR1C1%2520AKR1C2%2520AKR1C4%2520CYP3A4%2520CYP3A43%2520CYP3A5%2520CYP3A7%2520UGT2B15%2520UGT2B17%2520UGT2B7&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ccle_broad_2019_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ccle_broad_2019_mutations&heatmap_track_groups=ccle_broad_2019_CCLE_drug_treatment_IC50%2CAfatinib-2%2CAKTinhibitorVIII-1%2CAvagacestat-1&show_samples=false&tab_index=tab_visualize&treatment_list=Afatinib-2%3BAKTinhibitorVIII-1%3BAvagacestat-1

# Before
image

# After
image

### CODE REVIEW

**Comment by alisman** [comment]
https://6664-92735261-gh.circle-artifacts.com/0/imageCompare.html looks like there's trouble fitting these into the charts.  Might need to integrate length into chart width.  If so, there is already a method @adamabeshouse uses to get a pixel width for text.

**Comment by adamabeshouse** [comment]
@pvannierop check out TextTruncationUtils.ts::truncateWithEllipsis

Theres another method in that file that might be useful which for some reason (looks like maybe some unnoticed IDE shenanigans?) is currently called textTruncationUtils but should really be called "wrapText" which splits up the given text into an array where each element is less than the given maxWidth. you can feed that directly into victory as axis label text, which will stack the elements of the array as labels on top of each other.

**Comment by pvannierop** [comment]
@adamabeshouse  @alisman Thnx for your feedback. I implemented the following additions:
- Titles wrap when exceeding the plot boundaries
- Axis labels show the treatment name (not stable id)
- Axis labels wrap when exceeding the plot dimensions

**Comment by alisman** [comment]
@pvannierop just wanted to check one thing here.   see how legend shows white diamonds with label >8.0.     But the data points show up at 0.8.   Is this right?  Oh maybe it's due to log10?

image

**Comment by pvannierop** [comment]
@alisman  Yes, this is log10-transformed.

**Pull request merged**
